### ISSUE TITLE
If no args specified, nothing happens, and it just hangs over there

### ISSUE THREAD

**Issue by Jailman** [thimoonxy/go-pssh#1]
This is my solution, wonder if it is ok?
        if len(os.Args) >= 2 {
                // Pre-Processing
                runtime.GOMAXPROCS(runtime.NumCPU())
                auth := []ssh.AuthMethod{}
                ReadKey(*sshkey, &auth)
                PassWd := ssh.Password(*password)
                auth = append(auth, PassWd)

                std := StdJudge(os.Stdin, global_timeout) //error
                hostlist := HostListGen(std, *default_port)
                Conf := &ssh.ClientConfig{User: *username, Auth: auth, Timeout: conn_timeout}

                // Processing

                if *async {
                        fmt.Println("Async Mode running ...")
                        Run(hostlist, *onetime, Conf)
                } else {
                        fmt.Println("Sync Mode running ...")
                        RunCtl(hostlist, *onetime, Conf)
                }
        } else {
                fmt.Println("Use -h or --help for help!")
                os.Exit(1)
        }

**Comment by thimoonxy** [comment]
Fixed in commit ab6cc20fdd4e36c31cb77aa398c6c915e4c5f015.

Thx
