### ISSUE TITLE
Probably there should be an arg which specifies host file

### ISSUE THREAD

**Issue by Jailman** [thimoonxy/go-pssh#2]
Maybe this should work 

var (
                onetime, default_port        *int
                username, password, sshkey, hostfile   *string
                global_timeout, conn_timeout time.Duration
        )

 hostfile = flag.String("f", "/etc/hosts", "Host file. ")

                cmd := exec.Command("cat", *hostfile)
	        out, err := cmd.Output()
	        if err != nil {
		        fmt.Println(err)
	        }
	        // fmt.Println(string(out))
                r := bytes.NewReader(out)
                std := StdJudge(r, global_timeout)

**Comment by thimoonxy** [comment]
I've ever considered this but didn't want to over-cusomise it.
